# Generated by Django 5.0.4 on 2024-05-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0014_alter_messages_timestamp_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mutualFriends', models.IntegerField(default=0)),
            ],
        ),
    ]
