# Generated by Django 5.0.4 on 2024-05-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_server', '0015_friend'),
        ('backend_server', '0037_workouttype_created_at'),
    ]

    operations = [
    ]
